apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: Codsec-asp-marketplace-envs-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: CodSec ASP
    source:
      repo: https://github.com/CodSecIO/Codsec-asp-marketplace-envs.git
      sourceType: git
      dir: /terraform-marketplace
  ui:
    input:
      variables:
        backend_image_repo:
          name: backend_image_repo
          title: Backend Image Repo
        backend_image_tag:
          name: backend_image_tag
          title: Backend Image Tag
        cluster_location:
          name: cluster_location
          title: Cluster Location
        cluster_name:
          name: cluster_name
          title: Cluster Name
        create_cluster:
          name: create_cluster
          title: Create Cluster
        create_network:
          name: create_network
          title: Create Network
        db_availability_type:
          name: db_availability_type
          title: Db Availability Type
        db_deletion_protection:
          name: db_deletion_protection
          title: Db Deletion Protection
        db_disk_size:
          name: db_disk_size
          title: Db Disk Size
        db_name:
          name: db_name
          title: Db Name
        db_tier:
          name: db_tier
          title: Db Tier
        db_user:
          name: db_user
          title: Db User
        domain:
          name: domain
          title: Domain
        environment:
          name: environment
          title: Environment
        frontend_image_repo:
          name: frontend_image_repo
          title: Frontend Image Repo
        frontend_image_tag:
          name: frontend_image_tag
          title: Frontend Image Tag
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        helm_chart_name:
          name: helm_chart_name
          title: Helm Chart Name
        helm_chart_repo:
          name: helm_chart_repo
          title: Helm Chart Repo
        helm_chart_version:
          name: helm_chart_version
          title: Helm Chart Version
        helm_release_name:
          name: helm_release_name
          title: Helm Release Name
        ip_range_pods:
          name: ip_range_pods
          title: Ip Range Pods
        ip_range_services:
          name: ip_range_services
          title: Ip Range Services
        kubernetes_version:
          name: kubernetes_version
          title: Kubernetes Version
        name_prefix:
          name: name_prefix
          title: Name Prefix
        namespace:
          name: namespace
          title: Namespace
        network_cidr:
          name: network_cidr
          title: Network Cidr
        network_name:
          name: network_name
          title: Network Name
        node_machine_type:
          name: node_machine_type
          title: Node Machine Type
        node_max_count:
          name: node_max_count
          title: Node Max Count
        node_min_count:
          name: node_min_count
          title: Node Min Count
        node_pools:
          name: node_pools
          title: Node Pools
        project_id:
          name: project_id
          title: Project Id
        region:
          name: region
          title: Region
        regional:
          name: regional
          title: Regional
        subnetwork_name:
          name: subnetwork_name
          title: Subnetwork Name
        zone:
          name: zone
          title: Zone
        zones:
          name: zones
          title: Zones
