#==============================================
# GCP API Enablement
#==============================================

resource "google_project_service" "apis" {
  for_each = var.enable_apis ? toset([
    "sqladmin.googleapis.com",
  ]) : toset([])

  project                    = var.project_id
  service                    = each.value
  disable_on_destroy         = false
  disable_dependent_services = false
}

# ============================================================================
# POSTGRESQL CLOUDSQL INSTANCE
# ============================================================================

module "postgresql" {
  source = "terraform-google-modules/sql-db/google//modules/postgresql"
  # Vendored copy: bumped from 25.2 - that release caps google < 7 and the
  # vendored gke module requires >= 7.12.
  version = "27.2.0"

  depends_on = [google_project_service.apis]

  # Basic configuration
  name              = local.name
  project_id        = var.project_id
  database_version  = var.database_version
  region            = var.region
  tier              = var.tier
  availability_type = var.availability_type
  zone              = var.zone
  secondary_zone    = var.secondary_zone
  edition           = var.edition

  # Disk configuration
  disk_type             = var.disk.type
  disk_size             = var.disk.size
  disk_autoresize       = var.disk.autoresize
  disk_autoresize_limit = var.disk.autoresize_limit

  enable_random_password_special = var.enable_random_password_special

  ip_configuration = var.ip_configuration

  insights_config      = var.insights_config
  backup_configuration = var.backup_configuration

  maintenance_window_day  = var.maintenance_window.day
  maintenance_window_hour = var.maintenance_window.hour

  database_flags = local.database_flags_list

  deletion_protection = var.deletion_protection

  root_password       = var.root_user.password
  enable_default_user = var.root_user.enabled

  enable_default_db    = var.enable_default_db
  additional_databases = local.additional_databases_list

  additional_users = local.additional_users_list

  user_labels = var.labels

  connector_enforcement = var.connector_enforcement

  # Read replicas using our transformed list
  read_replicas = local.read_replicas

  master_instance_name = var.master_instance_name
}


# Vendored copy: the cloud_sql_auth_proxy VM module (appchoose/cloudsql-proxy)
# was removed - it caps the google provider below 7.x, and the Marketplace
# deployment connects over the VPC private IP, not through a proxy VM.

# ============================================================================
# SECRET MANAGER INTEGRATION
# ============================================================================

resource "google_secret_manager_secret" "root_password" {
  count = var.store_password_in_secret_manager ? 1 : 0

  project   = var.project_id
  secret_id = local.secret_id

  labels = var.labels

  replication {
    auto {}
  }

  depends_on = [module.postgresql]
}

resource "google_secret_manager_secret_version" "root_password" {
  count = var.store_password_in_secret_manager ? 1 : 0

  secret      = google_secret_manager_secret.root_password[0].name
  secret_data = var.root_user.password != null ? var.root_user.password : module.postgresql.generated_user_password

  depends_on = [module.postgresql]
}

# Store each additional user's password in Secret Manager (if enabled), using the password generated by the upstream module
resource "google_secret_manager_secret" "additional_user_passwords" {
  for_each = var.store_password_in_secret_manager ? { for name in var.additional_users : name => name } : {}

  project   = var.project_id
  secret_id = "${local.prefix}-psql-${each.key}"

  labels = merge(var.labels, {
    user = each.key
  })

  replication {
    auto {}
  }

  depends_on = [module.postgresql]
}

resource "google_secret_manager_secret_version" "additional_user_passwords" {
  for_each = var.store_password_in_secret_manager ? { for name in var.additional_users : name => name } : {}

  secret      = google_secret_manager_secret.additional_user_passwords[each.key].name
  secret_data = local.user_passwords_map[each.key]

  depends_on = [module.postgresql]
}
