# ============================================================================
# INSTANCE INFORMATION
# ============================================================================

output "instance_name" {
  description = "The name of the PostgreSQL instance"
  value       = module.postgresql.instance_name
}

output "instance_connection_name" {
  description = "The connection name of the PostgreSQL instance to be used in connection strings"
  value       = module.postgresql.instance_connection_name
}

output "instance_self_link" {
  description = "The URI of the PostgreSQL instance"
  value       = module.postgresql.instance_self_link
}

# ============================================================================
# CONNECTION INFORMATION
# ============================================================================

output "public_ip_address" {
  description = "The first public (PRIMARY) IPv4 address assigned to the PostgreSQL instance"
  value       = module.postgresql.public_ip_address
}

output "private_ip_address" {
  description = "The first private (PRIVATE) IPv4 address assigned to the PostgreSQL instance"
  value       = module.postgresql.private_ip_address
}

output "instance_ip_address" {
  description = "The IPv4 address assigned to the PostgreSQL instance"
  value       = module.postgresql.instance_ip_address
}

# ============================================================================
# GENERATED CREDENTIALS
# ============================================================================

output "root_password" {
  description = "Root password for the PostgreSQL instance (if auto-generated)"
  value       = module.postgresql.generated_user_password
  sensitive   = true
}

# ============================================================================
# SECRET MANAGER OUTPUTS
# ============================================================================

output "secret_manager_secret_id" {
  description = "The ID of the secret in Secret Manager (if enabled)"
  value       = var.store_password_in_secret_manager ? google_secret_manager_secret.root_password[0].secret_id : null
}

output "secret_manager_secret_name" {
  description = "The full name of the secret in Secret Manager (if enabled)"
  value       = var.store_password_in_secret_manager ? google_secret_manager_secret.root_password[0].name : null
}

output "additional_user_passwords" {
  description = "Map <username> ➜ password for additional DB users. Populated when passwords are generated by the upstream module or provided explicitly."
  value = {
    for u in module.postgresql.additional_users :
    u.name => u.password
  }
  sensitive = true
}
